apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: consignment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consignment
  template:
    metadata:
      labels:
        app: consignment
    spec:
        containers:
        - name: consignment-service
          image: 419011600616.dkr.ecr.us-east-1.amazonaws.com/consignment-service
          imagePullPolicy: Always
          command: [
            "./consignment-service",
            "--selector=static",
            "--server_address=:8080",
          ]
          env:
          - name: DB_HOST
            value: "mongo:27017"
          - name: UPDATED_AT
            value: "Tue 20 Mar 2018 08:53:19 GMT"
          ports:
          - containerPort: 8080
            name: cons-port