apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mongo-cluster-deployment
spec:
  replicas: 1 # this should always be 1
  template:
    metadata:
      labels:
        app: mongo-cluster
    spec:
      containers:
      - name: mongo-container
        image: mongo
        args: ["--dbpath", "/data/db"] # put your own path if it is different from a regular path
        ports:
        - name: mongo
          containerPort: 27017
          hostPort: 27017
        volumeMounts:
        - name: mongo-cluster-2a
          mountPath: /data
      volumes:
      - name: mongo-cluster-2a
        awsElasticBlockStore:
          volumeID: vol-09f4c61648e7ed33c
          fsType: ext4