apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mongo-cluster-deployment
spec:
  replicas: 1 # this should always be 1
  template:
    metadata:
      labels:
        app: mongo-cluster
    spec:
      containers:
      - name: mongo-container
        image: mongo
        args: ["--dbpath", "/data/db"] # put your own path if it is different from a regular path
        ports:
        - name: mongo
          containerPort: 27017
          hostPort: 27017
        volumeMounts:
        - name: mongo-persistent-storage
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: mongo-persistent-storage
      annotations:
        volume.beta.kubernetes.io/storage-class: "slow"
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi        